// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvmcHZdkEPJzO5doZ6eVEWM7aaik8Adc',
    appId: '1:445072558069:web:4adba3aab8ac182d33c2bc',
    messagingSenderId: '445072558069',
    projectId: 'memo-words-e2163',
    authDomain: 'memo-words-e2163.firebaseapp.com',
    storageBucket: 'memo-words-e2163.appspot.com',
    measurementId: 'G-R8M3FNR6L1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98LViPBbpqGRKXp4XKA4fWsijEd4vtXQ',
    appId: '1:445072558069:android:4f4dd772ddecdf9933c2bc',
    messagingSenderId: '445072558069',
    projectId: 'memo-words-e2163',
    storageBucket: 'memo-words-e2163.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVhBmKyr87DHqcrvCtq-tOs8Y1STwBqDs',
    appId: '1:445072558069:ios:dc270bbaf0664c9733c2bc',
    messagingSenderId: '445072558069',
    projectId: 'memo-words-e2163',
    storageBucket: 'memo-words-e2163.appspot.com',
    iosBundleId: 'com.example.memoWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVhBmKyr87DHqcrvCtq-tOs8Y1STwBqDs',
    appId: '1:445072558069:ios:98136d2d3acb7f7533c2bc',
    messagingSenderId: '445072558069',
    projectId: 'memo-words-e2163',
    storageBucket: 'memo-words-e2163.appspot.com',
    iosBundleId: 'com.example.memoWords.RunnerTests',
  );
}
